### ISSUE TITLE
Ругается на ошибку в собственном коде

### ISSUE THREAD

**Issue by Teashrock** [MGWL/asc1251#3]
Выдал ошибку уже при попытке скомпилировать с импортом самого себя. Лог прилагаю ниже.

************  Building D project: Yay  ************
Cleared problem markers for Yay.
\>\> Running `(default)` with: dub build
Performing "debug" build using C:\Program Files (x86)\D\dmd2\windows\bin\dmd.exe for x86.
yay ~master: building configuration "application"...
src\asc1251.d(534,25): Error: instead of C-style syntax, use D-style `char[][sByte] mm1251_Utf8`
src\asc1251.d(590,17): Error: instead of C-style syntax, use D-style `int[sByte] mm1251`
C:\Program Files (x86)\D\dmd2\windows\bin\dmd.exe failed with exit code 1.
  ^^^ Terminated, exit code: 2 ^^^
************  Build terminated.  ************

**Comment by MGWL** [comment]
Следует воспользоваться файлом:
https://github.com/MGWL/QtE5/tree/master/source/asc1251.d

Дело в том, что этот файл есть часть QtE5. Он конечно может быть использован самостоятельно,
но поддеживать его в двух репо слишком обременительно.
